import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang='ru'>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Xasanov Javohir xasanof17@gmail.com" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body className='bg-white font-inter'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}