export {default as Navbar} from './Navbar'
export {default as Footer} from './Footer'
export {default as Form} from './Form'
export {default as WhoSee} from './WhoSee'
export {default as WhatIsAd} from './WhatIsAd'
export {default as StepWork} from './StepWork'
export {default as WhatWin} from './WhatWin'